---
title: "Symulacje stochastyczne 4"
author: "Aleksandra Dąbrowska"
date: "20 March 2017"
output: html_document
---

Lancuch Markowa dla przestrzeni X={0,1,2,...}
Schemat urnowy.
```{r}

a<- 1
b<- 1

x <-c()

n<-1000
x[1] <- 0
symulacje <- function(a,b){
for (i in 1:n){
  x<- x[i]
  biala <- (a+x)/(a+b+i)
  u <- runif(1)
  x <- ifelse(u<=biala, x+1, x)
  x[i+1] <- x
}
  return(x)
}

plot(x)


#chcemy znalezc rozklad ostatnich wartosci

ostatnia <- function(a,b){
  x <-c()
n<-1000
x[1] <- 0
for (i in 1:n){
  x <- x[i]
  biala <- (a+x)/(a+b+i)
  u <- runif(1)
  x <- ifelse(u<biala, x+1, x)
  x[i+1] <- x
  }
  return(x[n+1])
}

#ostatnie <- replicate(500,ostatnia(1,1))

#hist(ostatnie, prob=TRUE)
#tu ma wyjsc jednostajny czyli beta(1,1)


#wykonujemy dzielenie wektora przez poszczegolna liczbe krokow.
x1 <- symulacje(1,1)

liczby <- c(1:1001)

dzielenie <- x1/liczby

plot(dzielenie)
  

#inne dane

x2 <- symulacje(2,3)


#chcemy zbieznosc od bety(a,b)
#maja to byc zbieznosci ogonow


ostatnie <- replicate(1000,ostatnia(2,3))

hist(ostatnie, prob=TRUE)
curve(dbeta(x,2,3),add=TRUE)




  
```



```{r}
#chcemy lancuch markowa dla AR(1)
n <- 20
x <- c()
x[1] <- 0
ro <- 0.9
for (i in 1:n){
  w <- rnorm(1)
  x[i+1] <- x[i]*ro + w
}


# pokazac ze rozkald nie zalezy od stanu poczatkowego
#pokombinowac z roznymi ro

#zrobic zadanko to co na wykladzie z alfa i beta i dwoma stanami


#robimy dluga trajektorie dla łańcucha z dwoma stanami
a<- 0.2
b<- 0.4

x <-c()

n<-1000
x[1] <- 1
symulacje <- function(a,b){
for (i in 1:n){
  u <- runif(1)
  x[i+1] <- ifelse(x[i]==1,ifelse(u<a,2,1),ifelse(u<b,1,2))
}
  return(x)
}


x <-symulacje(a,b)

liczba <-c(1:1001)

x_n <-x/liczba

table(x)



x1 <- symulacje(0.1,0.1)
barplot(x1)
table(x1)

x2 <- symulacje(0.5,0.5)
table(x2)


#srednia i wariancja

x2 <- symulacje(0.5,0.5)
mean(sum(x2)/101)#jakos 1.5
#(sd(sum(x2)/101))^2

suma <- cumsum(x2)
suma <- suma/liczba
plot(suma,type="l")



#teraz chcemy punkt poczatkowy losowac z rozkladu stacjonarnego
#x0 z rozkaldu dwupunktowego


x3 <- symulacje(0.9,0.9)
suma2 <- cumsum(x3)
suma2 <- suma2/liczba


x4 <- symulacje(0.1,0.1)
suma3 <- cumsum(x4)
suma3 <- suma3/liczba


plot(suma, type="l",col="blue")
plot(suma2, type="l", col="red")
plot(suma3, type="l",col="green")


#zbadac asymptotyczna wariancje
m <- 1000
powtorzenia <- replicate(m, symulacje(0.5,0.5))



powtorzenia2 <- replicate(10000,{
  x <-symulacje(0.5,0.5)
  liczby <- c(1:1001)
  sk <- cumsum(x)/liczby}
  )


var(powtorzenia2)


```

